services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: irmos_api
    restart: unless-stopped
    env_file: .env
    environment:
      DB_URL: sqlite:////data/midspan_data.db
      CSV_PATH: /data/midspan_data.csv
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    working_dir: /app/api
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --workers 1

  loader:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      DB_URL: sqlite:////data/midspan_data.db
      CSV_PATH: /data/midspan_data.csv
      TABLE_NAME: ${TABLE_NAME:-midspan_data}
      MODE_DB: ${MODE_DB:-replace}
    volumes:
      - ./data:/data
    working_dir: /app
    command: >
      python data/load_csv_to_db.py
    restart: "no"
    profiles: ["init"]
